---
- hosts: 192.168.5.100
  vars:
    - ports: "{{ 9090 }}"
  tasks:
  - name: install wget
    yum: name=wget state=present
  - name: install openjdk
    yum:  name=java-1.8.0-openjdk state=present
  - name: download jenkins.repo
    get_url:
      url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: import jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: install jenkins
    yum: name=jenkins  state=present
  - name: port replace
    replace:
      path: /etc/sysconfig/jenkins
      regexp: JENKINS_PORT="8080"
      replace: JENKINS_PORT="{{ports}}"
  - name: start jenkins
    systemd: name=jenkins state=started
  - name: enable jenkins
    systemd: name=jenkins enabled=true
  - name: firewalld
    firewalld: port={{ ports }}/tcp  permanent=true state=enabled
  - name: reload the firewalld
    systemd: name=firewalld state=reloaded
  - name: sleep for 30 seconds and continue with play
    wait_for: timeout=30
    delegate_to: localhost
  - name: init password jenkin
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result1
  - name: print init password jenkins
    debug:
      var: result1.stdout
